using System.Text;
using EconomyBot.Worker.Core;
using EconomyBot.Worker.Models;
using EconomyBot.Worker.Services;
using TL;

namespace EconomyBot.Worker.Features;

public class RentFeature(RentService rentService, NotificationQueue notificationQueue) : FeatureBase(notificationQueue), ICommandFeature
{
    public string CommandName => "Claim Rent";
    public IEnumerable<string> Aliases => new[] { "ecoclaim", "eco_rent_claim" };
    public string Description => "Claim passive rent generated by your assets. Usage: /ecoclaim";

    public async Task<bool> ExecuteAsync(EconomyCommand cmd, UserAccount account)
    {
        // First update pending rent
        await rentService.UpdatePendingRentAsync(account);

        if (cmd.CommandType == "eco_rent_claim")
        {
            var (resetAmount, tax) = rentService.ResetGenerator(account);
            if (resetAmount > 0)
            {
                var sb = new StringBuilder();
                sb.AppendLine($"✅ Successfully reset your generator! It can now produce another **$1,000,000**.");
                if (tax > 0)
                {
                    sb.AppendLine($"💸 You paid **${FormatNumber(tax)}** in property taxes upon reset.");
                }
                sb.AppendLine($"\nCurrent Balance: **${FormatNumber(account.Balance)}**");

                await Reply(cmd, sb.ToString());
                return true; // mutated
            }
            else
            {
                await Reply(cmd, "⚠️ Your generator is already at $0.");
                return true; // well, we did update rent timestamp at least
            }
        }

        // Handle /ecoclaim
        var sbInfo = new StringBuilder();
        sbInfo.AppendLine("🏢 **PASSIVE INCOME GENERATOR**\n");

        bool hasAssets = account.Inventory != null && account.Inventory.Count > 0;

        if (account.Balance < 1_000_000)
        {
            if (!hasAssets)
            {
                sbInfo.AppendLine("Your vault is currently empty.\n");
                sbInfo.AppendLine("Buy assets in the `/ecomarket` to start earning passive income!");
            }
            else
            {
                sbInfo.AppendLine("✨ **Unlimited Generation!**");
                sbInfo.AppendLine("Since your balance is under **$1M**, your rent is automatically claimed without any limits.\n");
                sbInfo.AppendLine("Your passive income flows directly into your balance! No need to refresh.");
                sbInfo.AppendLine($"\nCurrent Balance: **${FormatNumber(account.Balance)}**");
            }
            await Reply(cmd, sbInfo.ToString());
        }
        else
        {
            if (account.RentGeneratorFilled > 0)
            {
                if (!hasAssets)
                {
                    sbInfo.AppendLine($"You have a filled generator from previous assets: **${FormatNumber(account.RentGeneratorFilled)}** / **$1M** limit");
                }
                else
                {
                    sbInfo.AppendLine($"Your generator is currently filled: **${FormatNumber(account.RentGeneratorFilled)}** / **$1M** limit");
                }
                
                if (account.RentGeneratorFilled >= 1_000_000)
                {
                    sbInfo.AppendLine("⚠️ **Your generator is FULL! Reset now to keep earning.**");
                }
                
                if (!hasAssets)
                {
                    sbInfo.AppendLine("\nBuy assets in the `/ecomarket` to start earning passive income again!");
                }
                
                sbInfo.AppendLine("\nYour passive income automatically flows into your balance. Click the button below to reset your generator limit to $0 so it can keep producing.");
                
                var markup = new ReplyInlineMarkup
                {
                    rows = new[]
                    {
                        new KeyboardButtonRow
                        {
                            buttons = new KeyboardButtonBase[]
                            {
                                new KeyboardButtonCallback
                                {
                                    text = $"🔄 Reset Generator (${FormatNumber(account.RentGeneratorFilled)} filled)",
                                    data = Encoding.UTF8.GetBytes($"eco_rent_claim:{account.UserId}")
                                }
                            }
                        }
                    }
                };
                await Reply(cmd, sbInfo.ToString(), markup);
            }
            else
            {
                sbInfo.AppendLine("Your vault is currently empty.\n");
                if (hasAssets)
                {
                    sbInfo.AppendLine("Your assets are still generating rent... check back a bit later once they've accumulated at least $1!");
                }
                else
                {
                    sbInfo.AppendLine("Buy assets in the `/ecomarket` to start earning passive income!");
                }
                await Reply(cmd, sbInfo.ToString());
            }
        }

        return true;
    }

    // Hide FormatMoney from FeatureBase if it conflicts, or just remove if we use base.FormatNumber.
    // I'll just remove the local method since FeatureBase provides FormatNumber.
}
