using System.Text;
using EconomyBot.Worker.Core;
using EconomyBot.Worker.Models;
using EconomyBot.Worker.Services;
using TL;

namespace EconomyBot.Worker.Features;

public class RentFeature(RentService rentService, NotificationQueue notificationQueue) : FeatureBase(notificationQueue), ICommandFeature
{
    public string CommandName => "Claim Rent";
    public IEnumerable<string> Aliases => new[] { "ecoclaim", "eco_rent_claim" };
    public string Description => "Claim passive rent generated by your assets. Usage: /ecoclaim";

    public async Task<bool> ExecuteAsync(EconomyCommand cmd, UserAccount account)
    {
        // First update pending rent
        await rentService.UpdatePendingRentAsync(account);

        if (cmd.CommandType == "eco_rent_claim")
        {
            var (claimed, tax) = rentService.ClaimRent(account);
            if (claimed > 0)
            {
                var sb = new StringBuilder();
                sb.AppendLine($"✅ Successfully refreshed your generator! **${FormatNumber(claimed)}** was passively added to your balance.");
                if (tax > 0)
                {
                    sb.AppendLine($"💸 You paid **${FormatNumber(tax)}** in property taxes upon refresh.");
                }
                sb.AppendLine($"\nNew Balance: **${FormatNumber(account.Balance)}**");

                await Reply(cmd, sb.ToString());
                return true; // mutated
            }
            else
            {
                await Reply(cmd, "⚠️ You have no rent to claim right now!");
                return true; // well, we did update rent timestamp at least
            }
        }

        // Handle /ecoclaim
        var sbInfo = new StringBuilder();
        sbInfo.AppendLine("🏢 **PASSIVE INCOME GENERATOR**\n");

        if (account.Balance < 1_000_000)
        {
            sbInfo.AppendLine("✨ **Unlimited Generation!**");
            sbInfo.AppendLine("Since your balance is under **$1M**, your rent is automatically claimed without any limits.\n");
            sbInfo.AppendLine("Your passive income flows directly into your balance! No need to refresh.");
            sbInfo.AppendLine($"\nCurrent Balance: **${FormatNumber(account.Balance)}**");
            await Reply(cmd, sbInfo.ToString());
        }
        else
        {
            if (account.UnclaimedRent > 0)
            {
                sbInfo.AppendLine($"Your assets have passively generated: **${FormatNumber(account.UnclaimedRent)}** / **$1M** limit");
                if (account.UnclaimedRent >= 1_000_000)
                {
                    sbInfo.AppendLine("⚠️ **Your generator is FULL! Refresh now to earn more.**");
                }
                sbInfo.AppendLine("\nRent is automatically added to your balance. Click the button below to refresh your generator's limit.");
                
                var markup = new ReplyInlineMarkup
                {
                    rows = new[]
                    {
                        new KeyboardButtonRow
                        {
                            buttons = new KeyboardButtonBase[]
                            {
                                new KeyboardButtonCallback
                                {
                                    text = $"🔄 Refresh Generator (${FormatNumber(account.UnclaimedRent)})",
                                    data = Encoding.UTF8.GetBytes($"eco_rent_claim:{account.UserId}")
                                }
                            }
                        }
                    }
                };
                await Reply(cmd, sbInfo.ToString(), markup);
            }
            else
            {
                bool hasAssets = account.Inventory.Count > 0; // simplistic check
                sbInfo.AppendLine("Your vault is currently empty.\n");
                if (hasAssets)
                {
                    sbInfo.AppendLine("Your assets are still generating rent... check back a bit later once they've accumulated at least $1!");
                }
                else
                {
                    sbInfo.AppendLine("Buy assets in the `/ecomarket` to start earning passive income!");
                }
                await Reply(cmd, sbInfo.ToString());
            }
        }

        return true;
    }

    // Hide FormatMoney from FeatureBase if it conflicts, or just remove if we use base.FormatNumber.
    // I'll just remove the local method since FeatureBase provides FormatNumber.
}
